### ISSUE TITLE
Error while processing

### ISSUE THREAD

**Issue by dahakafury** [egorvas/ci_to_telegram#1]
Hi!
When I am trying to execute the ci_to_telegram.py, I got an error:
 python ci_to_telegram.py 
/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/user/Downloads/telegram-bot/credentials/email_to_telegram.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "ci_to_telegram.py", line 115, in <module>
    main()
  File "ci_to_telegram.py", line 42, in main
    credentials = get_credentials()
  File "ci_to_telegram.py", line 33, in get_credentials
    if flags:
NameError: global name 'flags' is not defined

Any ideas how to solve this issue?
Thanks..

**Comment by dahakafury** [comment]
I find solution! After **import requests** I add next:
`
try:
    import argparse
    flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
except ImportError:
    flags = None
`
